# ROUTER_PATH = '../views/'

[[R]]
name = "login"
title = "login"
path = "/login"
router = "login"
  
# [[R]]
# name = "index"
# title = "index"
# path = "/"
# router = "hospital/index"
# [R.meta]
# requiresAuth = true

[[R]]
name = "tabbar"
title = "mint-tabbar"
path = "/"
router = "mint/tabbar"
[R.meta]
requiresAuth = true