# ROUTER_PATH = '../views/'

[[R]]
name = "login"
title = "login"
path = "/login"
router = "login"
  
[[R]]
name = "index"
title = "index"
path = "/"
router = "index"
[R.meta]
requiresAuth = true

[[R]]
name = "tabbar"
title = "mint-tabbar"
path = "/mint-tabbar"
router = "mint/tabbar"
[R.meta]
requiresAuth = true